### PR TITLE
supporting service status on ubuntu, loosening dependency configuration

### PR DESCRIPTION
**Pull request by jonoterc**
This address issue #8. Implemented service status detection for Ubuntu/Debian (for some reason this isn't supported by the system netatalk package, worked around with a shell one-liner).

Also, configured dependencies were way out of date; loosened these up for better compatibility with latest version.

### CODE REVIEW

**Comment by ryanycoleman** [comment]
Hey @jonoterc thanks for your contributions. I had accidentally turned off email notifications for this repo and only just noticed your PRs. I'll give them some attention later this week. Thanks!

**Comment by jonoterc** [comment]
Cool, thanks!

**Comment by ryanycoleman** [comment]
I cherry-picked 8cbd4a0ab57018fa593d0bcb4c02f01f1d630ff0 into master, leaving behind the module dependency commit which was addressed separately. Thank you for splitting your commits and of course for the contribution. I really appreciate it and apologize for taking so long to incorporate them.

**Comment by jonoterc** [comment]
No worries about the delays, and thanks much!

**Pull request closed without merging**
